default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: devise_trial_development

test:
  <<: *default
  database: devise_trial_test

production:
  <<: *default
  database: devise_trial_production
